name: CMake Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}} \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTS=ON
      
    - name: Build project
      run: |
        cmake --build ${{github.workspace}}/build --config Release --parallel 2
      
    - name: Run tests
      run: |
        cd ${{github.workspace}}/build
        ctest --output-on-failure
